#!/bin/bash
shopt -s extglob

case $# in
    0)	echo "Not enough arguments"
	;;

    1)	case $1 in
	remove) delgroup ezkvm
		rm -f /etc/security/limits.d/92-ezkvm.conf
		rm -rf /var/ezkvm
		rm -rf /usr/share/ezkvm
		chmod -s /usr/lib/qemu/qemu-bridge-helper
		;;

	purge)	rm -rf /etc/ezkvm
		;;

	*)	echo "Option '$1' not supported"
		;;
	esac
	;;

    *)	echo "Too many arguments"
    	;;
esac
